### ISSUE TITLE
Gets stuck on screen

### ISSUE THREAD

**Issue by mcg** [musa11971/Music-Bar#28]
Sometimes I will click on the menubar icon to show/control playback and when I click away the artwork/control window will not disappear. Also it would be nice if clicking the menubar icon would toggle show/hide. Currently if you click it when the window is open, it re-opens instead of hiding.

**Comment by mcg** [comment]
To reproduce the "stuck on screen" issue. Open from menubar, select prefs, close prefs. The next time the window opens it will not close when clicking away.

**Comment by musa11971** [comment]
[v1.3](https://github.com/musa11971/Music-Bar/releases/tag/v1.3) changed some of the popover behavior.

Do you still experience these issues in v1.3, @mcg?

**Comment by mcg** [comment]
Looks like the "stuck" issue is fixed. Thanks!

**Comment by musa11971** [comment]
Great 😃 

> Also it would be nice if clicking the menubar icon would toggle show/hide. Currently if you click it when the window is open, it re-opens instead of hiding.

This has been implemented and will be available in the next update.
