### ISSUE TITLE
Clicking MusicBar icon again to close menu

### ISSUE THREAD

**Issue by petebocken** [musa11971/Music-Bar#33]
Steps to reproduce:
1. Click MusicBar menu icon to open MusicBar
2. Click MusicBar menu icon a second time to close MusicBar, does not close it.

Being able to close a menubar menu by clicking it again is considered standard behavior.

**Comment by musa11971** [comment]
Thank you for reporting this issue.

Happy to tell you the fix for this has been implemented and will be available in the next release.

**Comment by petebocken** [comment]
Just installed v1.3.1 and it appears the issue is partially fixed. I can still reproduce the issue.

Screen recording: https://p110.p2.n0.cdn.getcloudapp.com/items/7Kuy6pXQ/Screen+Recording+2020-01-10+at+08.22+AM.mov

**Comment by derekschrock** [comment]
Able to reproduce this as well.
