### ISSUE TITLE
Spotify support?

### ISSUE THREAD

**Issue by dscos** [musa11971/Music-Bar#36]
Do you have any plans to add Spotify support? I use both Spotify and Music and it would be great to have one app do both. Obviously I would be willing to donate something toward that effort.

**Comment by musa11971** [comment]
Thanks for writing in @dscos.

I've looked at "competing" apps that provide Spotify support, but to be frank their codebases are messy and it causes an unnecessary amount of overhead on the app. 

Maybe I can seriously consider Spotify support if anyone can come up with a clean and efficient way of adding it, without degrading the app's current performance. What it comes down is a simple case of quality over quantity, I suppose...

That being said, for now I will unfortunately have to limit Music Bar to being exclusively available for use with Apple Music.
