### ISSUE TITLE
Mojave support

### ISSUE THREAD

**Issue by dvrooman** [musa11971/Music-Bar#38]
Is there any chance of getting Mojave support?

**Comment by musa11971** [comment]
@dvrooman Let's see if we can do that 😃 

I've built a version for Mojave. Could you please see if it works as expected? Let me know how that goes by replying on this issue. If everything runs fine, I'll tag a new version of the app with Mojave support. 


[Music.Bar-MOJAVE-TEST.zip](https://github.com/musa11971/Music-Bar/files/4606383/Music.Bar-MOJAVE-TEST.zip)

**Comment by dvrooman** [comment]
@musa11971 You're amazing!

Unfortunately, I the test app still gives an error message saying I need macOS 10.15 or later and the app icon is crossed out.

![Screen Shot 2020-05-10 at 2 19 22 PM](https://user-images.githubusercontent.com/2829985/81507226-e7027080-92c9-11ea-9c71-188ab33ca756.png)
![Screen Shot 2020-05-10 at 2 23 45 PM](https://user-images.githubusercontent.com/2829985/81507232-ebc72480-92c9-11ea-812b-89d966c03922.png)

**Comment by musa11971** [comment]
That doesn't look good. Could you try this build?

[Music.Bar-MOJAVE-TEST-2.zip](https://github.com/musa11971/Music-Bar/files/4606523/Music.Bar-MOJAVE-TEST-2.zip)

**Comment by dvrooman** [comment]
That works! Now the only problem is that I'm a fool and didn't read the description of the app closely enough. I was looking for something to control Spotify. I swear I followed a link from a discussion about such an app, but it looks like Music Bar only supports Apple Music? I don't have an Apple Music subscription, so other than confirming that the application launches, I can't tell you if it's working properly. Sorry about that!

**Comment by musa11971** [comment]
Heh, no worries! Yes, Music Bar indeed only supports Apple Music. 

Anyways... Mojave support added in v1.3.3 😎.
