### ISSUE TITLE
Mojave iTunes integration issues

### ISSUE THREAD

**Issue by triangulum** [musa11971/Music-Bar#43]
Firstly, thanks for adding Mojave support, that's been the biggest barrier to trying MusicBar so far! I have, however, noticed some major issues with functionality.

#### What does work:
- playing and pausing by clicking on the album art
- skip previous and next

#### What doesn't work:

- album art (it never loads)
- song information (it doesn't display in the window or menubar)
- playback status (the scroller is always 0:00, track length is always 3:26)
- play/pause button state (it always stays on ▶)

![menubar](https://user-images.githubusercontent.com/22440652/82175878-7b974f00-9918-11ea-9f99-8453a7b474ab.png)
![window](https://user-images.githubusercontent.com/22440652/82175871-7934f500-9918-11ea-90ea-a5bd178216d2.png)

---

Regarding the album art, it might be interesting to look at the implementation used by [NepTunes](https://github.com/rurza/NepTunes). 

Ultimately, if NepTunes had a menubar window, in addition to its floating desktop window, this would almost make MusicBar/alternatives superfluous. Have you thought about integrating your MusicBar functionality together with the NepTunes? (On a tangent, their Spotify support might also be interesting.)

**Comment by musa11971** [comment]
Sounds like an issue with AppleScript, but unsure what could be causing this. No other reports on this issue, so this will be closed for now.

Could be related to #45
