### ISSUE TITLE
Big Sur: track details not shown if track is not in library

### ISSUE THREAD

**Issue by BartmanEH** [musa11971/Music-Bar#45]
was working fine on Catalina. upgraded to Big Sur now doesn't show anything in menu bar and only shows track time when I click it in menu bar and even that is not accurate

**Comment by musa11971** [comment]
Strange, I just updated to Big Sur (11.0.1) and Music Bar seems to be working fine... Do you know if there could be anything else breaking the app?

**Comment by egar0** [comment]
Same issue as @BartmanEH.  It may have worked just after the Big Sur upgrade, I'm not sure about that though.  Definitely does not work now.   Can only see artist and track when I click on the icon in the menu bar.  I have version 1.3.3

**Comment by musa11971** [comment]
@egar0 What macOS version?

**Comment by egar0** [comment]
MacOS 11.0.1 (Big Sur)

**Comment by kiritokatklian** [comment]
I noticed that the app works correctly with my own playlists, but doesn't work when using online features such as from search, browse tab, radio tab, etc. The app behaves correctly on Catalina, so maybe an error on Apple's side?

**Comment by egar0** [comment]
I’ve only tried it with browse and radio. I’ll try it with my music library to see if I can duplicate your findings.

**Comment by wutzetown** [comment]
> I noticed that the app works correctly with my own playlists, but doesn't work when using online features such as from search, browse tab, radio tab, etc. The app behaves correctly on Catalina, so maybe an error on Apple's side?

same observation. No problem with Catalina. Use MacOS 11.0.1 (Big Sur)

**Comment by alombi** [comment]
I've noticed that both Automator and AppleScript are broken when looking for current song if it isn't added to the user's library. I had this problem with various other apps that used to collect current song, even with some apps I was developing. 
I found the bug back in BigSur's Beta and I've immediately reported to Apple. No response from them, neither bug fixing (unfortunately).

**Comment by musa11971** [comment]
Confirmed problem with AppleScript. Unsure whether this is an intentional change by Apple, or a bug on their side. 

Track is in library:
<img width="812" alt="in-library" src="https://user-images.githubusercontent.com/21341801/101769690-a41aac80-3ae7-11eb-9ad5-4e266c536eb7.png">

Track is not in library:
<img width="812" alt="not-in-library" src="https://user-images.githubusercontent.com/21341801/101769702-a977f700-3ae7-11eb-8413-52c117161a0e.png">

**Comment by alombi** [comment]
MacOS 11.1 is out but the issue is still unsolved.

**Comment by bdonovan88** [comment]
same here with macOS 11.2.1. noticed when it didn't display track names when listening to curated 'radio stations'.

**Comment by brentredd** [comment]
the issue is fixed for me in macOS 11.3

**Comment by bdonovan88** [comment]
> the issue is fixed for me in macOS 11.3

thanks for the heads up. just tested on 11.3 and working for me too!

**Comment by alombi** [comment]
That's great news! Thank you

**Comment by musa11971** [comment]
Glad Apple fixed it!
