### ISSUE TITLE
Can't open, getting warning from macOS

### ISSUE THREAD

**Issue by edalzell** [musa11971/Music-Bar#56]
I see this when I launch it: 
<img width="263" alt="image" src="https://user-images.githubusercontent.com/6069653/102524179-7684b480-404d-11eb-97d2-c68f635c8f08.png">

Do you have plans to properly sign the app?

**Comment by musa11971** [comment]
No plans on "fixing" this. Installation instructions in the README describe how to bypass this warning. Only needs to be done on first open.
