### ISSUE TITLE
Icons are not visible

### ISSUE THREAD

**Issue by iceburgerburg** [musa11971/Music-Bar#59]
Can't see the setting icon, I knew the setting button is located at right upper corner after watching the demo video, while clicking at that position, the setting items can pop up.

<img width="257" alt="截屏2021-04-11下午7 54 11" src="https://user-images.githubusercontent.com/25301835/114303297-f1437500-9aff-11eb-93c6-cbec1a0b09ac.png">

**Comment by musa11971** [comment]
All icons are svg's so they should be able to render on any Mac.

Are you using the latest version of Music Bar (1.4)?
What version of macOS are you running?

**Comment by iceburgerburg** [comment]
Music Bar Version 1.4

**Comment by jandreaucodes** [comment]
I just downloaded the app and have the same issu.

Music Bar 1.4, macOS Catalina 10.15.7

**Comment by musa11971** [comment]
@iceburgerburg and @jandreaucodes. Could you please test if [this build](https://github.com/musa11971/Music-Bar/files/6815276/Music.Bar-DEBUG.zip) fixes the issue?

Thanks.

**Comment by musa11971** [comment]
This issue should be fixed. Will close this issue. Please re-open if you are still facing the issue.
