### ISSUE TITLE
Request: Controls below Artwork or Only on Hover

### ISSUE THREAD

**Issue by Xyth** [musa11971/Music-Bar#68]
I find the controls (and associated opacity layer) over the artwork aesthetically unpleasing and would prefer to have them in below the artwork. However, as a compromise could they not appear until the pointer is actually over the artwork? Often I'm just clicking the menu item to see the artwork, I don't need or want to see the controls yet.

**Comment by musa11971** [comment]
Hi, thanks for reporting the issue. I agree the current behavior is aesthetically unpleasing. It was in fact a bug and will be fixed in the next release! :)
